# Generated by Django 4.2.11 on 2024-05-20 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_pentest', models.IntegerField(choices=[(1, 'Web Application'), (2, 'Network'), (3, 'Cloud')])),
                ('type_software', models.IntegerField(choices=[(1, 'Web-based'), (2, 'Mobile'), (3, 'Network')])),
                ('platform', models.IntegerField(choices=[(1, 'Windows'), (2, 'Linux'), (3, 'macOS'), (4, 'Cloud')])),
                ('type_password_attack', models.IntegerField(choices=[(1, 'Brute Force'), (2, 'Dictionary'), (3, 'Hybrid')])),
                ('hash_type', models.IntegerField(choices=[(0, 'MD5'), (1, 'SHA-1'), (2, 'SHA-256')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
