# Generated by Django 4.2.11 on 2024-06-27 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Tool', '0002_alter_usersuggestion_goal_pentest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_pentest', models.CharField(max_length=255)),
                ('type_software', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=255)),
                ('type_password_attack', models.CharField(max_length=255)),
                ('hash_type', models.CharField(max_length=255)),
                ('suggested_tool_1', models.CharField(max_length=255)),
                ('suggested_tool_2', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSuggestion',
        ),
    ]
