# Generated by Django 4.2.11 on 2024-06-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool', '0003_userresult_delete_usersuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='disagree',
            field=models.BooleanField(default=False),
        ),
    ]
