# Generated by Django 4.2.11 on 2024-06-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tool', '0004_userresult_disagree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresult',
            name='disagree',
        ),
    ]
