# Generated by Django 4.2.11 on 2024-07-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool', '0005_remove_userresult_disagree'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='feedback',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
