# Generated by Django 4.2.11 on 2024-07-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool', '0006_userresult_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresult',
            name='feedback',
        ),
        migrations.AddField(
            model_name='userresult',
            name='status',
            field=models.CharField(choices=[('agree', 'Agree'), ('disagree', 'Disagree')], default='agree', max_length=10),
        ),
    ]
