# Generated by Django 4.2.11 on 2024-07-13 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tool', '0007_remove_userresult_feedback_userresult_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresult',
            name='status',
        ),
    ]
