# Generated by Django 4.2.11 on 2024-07-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tool', '0008_remove_userresult_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='user_agreed',
            field=models.BooleanField(default=True),
        ),
    ]
